# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestion_system.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestion_system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17suggestion_system.proto\x12\x0bsuggestions\"C\n\x0e\x42ookSuggestion\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05genre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\'\n\x11SuggestionRequest\x12\x12\n\nbook_title\x18\x01 \x01(\t\"F\n\x12SuggestionResponse\x12\x30\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x1b.suggestions.BookSuggestion2f\n\x11SuggestionService\x12Q\n\x0eGetSuggestions\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestion_system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKSUGGESTION']._serialized_start=40
  _globals['_BOOKSUGGESTION']._serialized_end=107
  _globals['_SUGGESTIONREQUEST']._serialized_start=109
  _globals['_SUGGESTIONREQUEST']._serialized_end=148
  _globals['_SUGGESTIONRESPONSE']._serialized_start=150
  _globals['_SUGGESTIONRESPONSE']._serialized_end=220
  _globals['_SUGGESTIONSERVICE']._serialized_start=222
  _globals['_SUGGESTIONSERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
