version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    environment:
      - PYTHONPATH=/app

  orchestrator:
    build:
      context: .
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - "8081:5000"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
      - PYTHONPATH=/app
      - BOOKS_DB_PRIMARY_ADDR=books_database_1:50060
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
      - ./utils/pb/suggestions:/app/suggestions
      - ./utils/pb/books_database:/app/utils/pb/books_database
    command: python orchestrator/src/app.py

  fraud_detection:
    build:
      context: .
      dockerfile: ./fraud_detection/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/fraud_detection/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./fraud_detection/src:/app/fraud_detection/src
    command: python fraud_detection/src/app.py

  transaction_verification:
    build:
      context: .
      dockerfile: ./transaction_verification/Dockerfile
    ports:
      - "50052:50052"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/transaction_verification/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./transaction_verification/src:/app/transaction_verification/src
    command: python transaction_verification/src/app.py

  suggestions:
    build:
      context: .
      dockerfile: ./suggestions/Dockerfile
    ports:
      - "50053:50053"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/suggestions/src/app.py
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./suggestions/src:/app/suggestions/src
    command: python suggestions/src/app.py

  order_queue:
    build:
      context: .
      dockerfile: ./order_queue/Dockerfile
    ports:
      - "50054:50051"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_queue/src/app.py
      - PYTHONPATH=/app:/app/utils/pb/order_queue
    volumes:
      - ./utils:/app/utils
      - ./order_queue/src:/app/order_queue/src
    command: python order_queue/src/app.py

  order_executor_1:
    build:
      context: .
      dockerfile: ./order_executor/Dockerfile
    container_name: order_executor_1
    environment:
      - EXECUTOR_ID=order_executor_1
      - EXECUTOR_PEERS=order_executor_1,order_executor_2,order_executor_3
      - EXECUTOR_PEER_ADDRS=order_executor_1:50052,order_executor_2:50052,order_executor_3:50052
      - ORDER_QUEUE_HOST=order_queue
      - ORDER_QUEUE_PORT=50051
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app:/app/utils/pb/books_database:/app/utils/pb/payment
      - BOOKS_DB_PRIMARY_ADDR=books_database_1:50060
      - PAYMENT_ADDR=payment:50061
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
    depends_on:
      - order_queue
      - books_database_1
      - books_database_2
      - books_database_3
      - payment
    command: python order_executor/src/app.py

  order_executor_2:
    build:
      context: .
      dockerfile: ./order_executor/Dockerfile
    container_name: order_executor_2
    environment:
      - EXECUTOR_ID=order_executor_2
      - EXECUTOR_PEERS=order_executor_1,order_executor_2,order_executor_3
      - EXECUTOR_PEER_ADDRS=order_executor_1:50052,order_executor_2:50052,order_executor_3:50052
      - ORDER_QUEUE_HOST=order_queue
      - ORDER_QUEUE_PORT=50051
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app:/app/utils/pb/books_database:/app/utils/pb/payment
      - BOOKS_DB_PRIMARY_ADDR=books_database_1:50060
      - PAYMENT_ADDR=payment:50061
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
    depends_on:
      - order_queue
      - books_database_1
      - books_database_2
      - books_database_3
      - payment
    command: python order_executor/src/app.py

  order_executor_3:
    build:
      context: .
      dockerfile: ./order_executor/Dockerfile
    container_name: order_executor_3
    environment:
      - EXECUTOR_ID=order_executor_3
      - EXECUTOR_PEERS=order_executor_1,order_executor_2,order_executor_3
      - EXECUTOR_PEER_ADDRS=order_executor_1:50052,order_executor_2:50052,order_executor_3:50052
      - ORDER_QUEUE_HOST=order_queue
      - ORDER_QUEUE_PORT=50051
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app:/app/utils/pb/books_database:/app/utils/pb/payment
      - BOOKS_DB_PRIMARY_ADDR=books_database_1:50060
      - PAYMENT_ADDR=payment:50061
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
    depends_on:
      - order_queue
      - books_database_1
      - books_database_2
      - books_database_3
      - payment
    command: python order_executor/src/app.py

  books_database_1:
    build:
      context: .
      dockerfile: ./books_database/Dockerfile
    container_name: books_database_1
    hostname: books_database_1
    ports:
      - "50055:50060"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app:/app/utils/pb/books_database
      - REPLICA_ID=books_database_1
      - PRIMARY_ID=books_database_1
      - REPLICA_PORT=50060
      - PEER_ADDRS=books_database_1:50060,books_database_2:50060,books_database_3:50060
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src
    command: python books_database/src/app.py

  books_database_2:
    build:
      context: .
      dockerfile: ./books_database/Dockerfile
    container_name: books_database_2
    hostname: books_database_2
    ports:
      - "50056:50060"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app:/app/utils/pb/books_database
      - REPLICA_ID=books_database_2
      - PRIMARY_ID=books_database_1
      - REPLICA_PORT=50060
      - PEER_ADDRS=books_database_1:50060,books_database_2:50060,books_database_3:50060
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src
    depends_on:
      - books_database_1
    command: python books_database/src/app.py

  books_database_3:
    build:
      context: .
      dockerfile: ./books_database/Dockerfile
    container_name: books_database_3
    hostname: books_database_3
    ports:
      - "50057:50060"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app:/app/utils/pb/books_database
      - REPLICA_ID=books_database_3
      - PRIMARY_ID=books_database_1
      - REPLICA_PORT=50060
      - PEER_ADDRS=books_database_1:50060,books_database_2:50060,books_database_3:50060
    volumes:
      - ./utils:/app/utils
      - ./books_database/src:/app/books_database/src
    depends_on:
      - books_database_1
    command: python books_database/src/app.py

  payment:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    container_name: payment
    hostname: payment
    # no ports exposed
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PAYMENT_PORT=50061
      - PYTHONPATH=/app
    volumes:
      - ./utils:/app/utils
      - ./payment/src:/app/payment/src
      - ./utils/pb/payment:/app/utils/pb/payment
    command: python payment/src/app.py
