# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\">\n\x15\x46raudDetectionRequest\x12\x14\n\x0c\x63heckoutData\x18\x01 \x01(\t\x12\x0f\n\x07orderId\x18\x02 \x01(\t\":\n\x16\x46raudDetectionResponse\x12\x0f\n\x07isFraud\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2v\n\x15\x46raudDetectionService\x12]\n\nCheckFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=42
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=104
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=106
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=164
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=166
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
