# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books_database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\x12\rbooksdatabase\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"E\n\x15\x44\x65\x63rementStockRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1d\n\x15quantity_to_decrement\x18\x02 \x01(\x05\">\n\x16\x44\x65\x63rementStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0b\x66inal_stock\x18\x02 \x01(\x05\"D\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tnew_stock\x18\x03 \x01(\x05\"1\n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"2\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"1\n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc8\x03\n\rBooksDatabase\x12?\n\x04Read\x12\x1a.booksdatabase.ReadRequest\x1a\x1b.booksdatabase.ReadResponse\x12\x42\n\x05Write\x12\x1b.booksdatabase.WriteRequest\x1a\x1c.booksdatabase.WriteResponse\x12]\n\x0e\x44\x65\x63rementStock\x12$.booksdatabase.DecrementStockRequest\x1a%.booksdatabase.DecrementStockResponse\x12H\n\x07Prepare\x12\x1d.booksdatabase.PrepareRequest\x1a\x1e.booksdatabase.PrepareResponse\x12\x45\n\x06\x43ommit\x12\x1c.booksdatabase.CommitRequest\x1a\x1d.booksdatabase.CommitResponse\x12\x42\n\x05\x41\x62ort\x12\x1b.booksdatabase.AbortRequest\x1a\x1c.booksdatabase.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=39
  _globals['_READREQUEST']._serialized_end=67
  _globals['_READRESPONSE']._serialized_start=69
  _globals['_READRESPONSE']._serialized_end=98
  _globals['_WRITEREQUEST']._serialized_start=100
  _globals['_WRITEREQUEST']._serialized_end=148
  _globals['_WRITERESPONSE']._serialized_start=150
  _globals['_WRITERESPONSE']._serialized_end=182
  _globals['_DECREMENTSTOCKREQUEST']._serialized_start=184
  _globals['_DECREMENTSTOCKREQUEST']._serialized_end=253
  _globals['_DECREMENTSTOCKRESPONSE']._serialized_start=255
  _globals['_DECREMENTSTOCKRESPONSE']._serialized_end=317
  _globals['_PREPAREREQUEST']._serialized_start=319
  _globals['_PREPAREREQUEST']._serialized_end=387
  _globals['_PREPARERESPONSE']._serialized_start=389
  _globals['_PREPARERESPONSE']._serialized_end=438
  _globals['_COMMITREQUEST']._serialized_start=440
  _globals['_COMMITREQUEST']._serialized_end=488
  _globals['_COMMITRESPONSE']._serialized_start=490
  _globals['_COMMITRESPONSE']._serialized_end=540
  _globals['_ABORTREQUEST']._serialized_start=542
  _globals['_ABORTREQUEST']._serialized_end=574
  _globals['_ABORTRESPONSE']._serialized_start=576
  _globals['_ABORTRESPONSE']._serialized_end=625
  _globals['_BOOKSDATABASE']._serialized_start=628
  _globals['_BOOKSDATABASE']._serialized_end=1084
# @@protoc_insertion_point(module_scope)
