# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/books_database/books_database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/books_database/books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/books_database/books_database.proto\x12\rbooksdatabase\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"E\n\x15\x44\x65\x63rementStockRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1d\n\x15quantity_to_decrement\x18\x02 \x01(\x05\">\n\x16\x44\x65\x63rementStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0b\x66inal_stock\x18\x02 \x01(\x05\x32\xf3\x01\n\rBooksDatabase\x12?\n\x04Read\x12\x1a.booksdatabase.ReadRequest\x1a\x1b.booksdatabase.ReadResponse\x12\x42\n\x05Write\x12\x1b.booksdatabase.WriteRequest\x1a\x1c.booksdatabase.WriteResponse\x12]\n\x0e\x44\x65\x63rementStock\x12$.booksdatabase.DecrementStockRequest\x1a%.booksdatabase.DecrementStockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.books_database.books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=63
  _globals['_READREQUEST']._serialized_end=91
  _globals['_READRESPONSE']._serialized_start=93
  _globals['_READRESPONSE']._serialized_end=122
  _globals['_WRITEREQUEST']._serialized_start=124
  _globals['_WRITEREQUEST']._serialized_end=172
  _globals['_WRITERESPONSE']._serialized_start=174
  _globals['_WRITERESPONSE']._serialized_end=206
  _globals['_DECREMENTSTOCKREQUEST']._serialized_start=208
  _globals['_DECREMENTSTOCKREQUEST']._serialized_end=277
  _globals['_DECREMENTSTOCKRESPONSE']._serialized_start=279
  _globals['_DECREMENTSTOCKRESPONSE']._serialized_end=341
  _globals['_BOOKSDATABASE']._serialized_start=344
  _globals['_BOOKSDATABASE']._serialized_end=587
# @@protoc_insertion_point(module_scope)
