# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/order_executor/order_executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/order_executor/order_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/order_executor/order_executor.proto\x12\rorderexecutor\"\x15\n\x13\x45xecuteOrderRequest\"8\n\x14\x45xecuteOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb4\x01\n\x14OrderExecutorService\x12[\n\x10\x45xecuteNextOrder\x12\".orderexecutor.ExecuteOrderRequest\x1a#.orderexecutor.ExecuteOrderResponse\x12?\n\x04Ping\x12\x1a.orderexecutor.PingRequest\x1a\x1b.orderexecutor.PingResponseB\x11Z\x0forderexecutorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_executor.order_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017orderexecutorpb'
  _globals['_EXECUTEORDERREQUEST']._serialized_start=63
  _globals['_EXECUTEORDERREQUEST']._serialized_end=84
  _globals['_EXECUTEORDERRESPONSE']._serialized_start=86
  _globals['_EXECUTEORDERRESPONSE']._serialized_end=142
  _globals['_PINGREQUEST']._serialized_start=144
  _globals['_PINGREQUEST']._serialized_end=157
  _globals['_PINGRESPONSE']._serialized_start=159
  _globals['_PINGRESPONSE']._serialized_end=190
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=193
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
