{
 "title": "Master",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traces",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# \n# 🚀 Explore Traces  \n[Go to Tempo Explore](/explore?left=Tempo)\n"
   }
  },
  {
   "title": "Dashboard Overview",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "## 📊 Dashboard Overview\n\nThis dashboard provides a one-page view of the key metrics and traces in your end-to-end checkout flow:\n\n- **Trace Explorer**  \n  Jump into Tempo to drill down on individual `/checkout` spans and see full service-to-service call traces.  \n\n- **Checkout Latency Heatmap**  \n  A bucketed view of end-to-end checkout response times (ms) over the last 5 minutes, showing where your requests cluster.  \n\n- **Fraud Checks/min**  \n  How many fraud-detection calls you’re making per minute.  \n\n- **Average Checkout Latency**  \n  The mean `/checkout` response time (ms) over the last minute.  \n\n- **Total Orders (last 15 min)**  \n  The total number of checkout orders processed in the past 15 minutes.  \n\n- **Checkout Latency P90 / P99**  \n  The 90th and 99th percentile end-to-end response times (ms) over the last 5 minutes.  \n\n- **Fraud-Check Duration P90 / P99**  \n  The 90th and 99th percentile durations (ms) of your fraud-detection calls over the last 5 minutes.  \n"
   }
  },
  {
   "title": "Checkout Latency Heatmap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(response_time_ms_bucket[5m])\r\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Fraud Checks/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(type)(\r\n  increase(fraud_checks_total[15m])\r\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Orders (last 15 min)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(\r\n  sum(increase(orders_total[15m]))\r\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average. Checkout Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(response_time_ms_sum[5m]))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Fraud-Check Duration P90",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.90,\r\n  sum by (le)(rate(fraud_check_duration_ms_bucket[5m]))\r\n)",
     "legendFormat": "{{P90}}"
    }
   ]
  },
  {
   "title": "Fraud-Check Duration P99",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(rate(fraud_check_duration_ms_bucket[5m]))\r\n)",
     "legendFormat": "{{P99}}"
    }
   ]
  },
  {
   "title": "Checkout Latency P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.90,\r\n  sum by (le)(rate(response_time_ms_bucket[5m]))\r\n)",
     "legendFormat": "{{P90}}"
    }
   ]
  },
  {
   "title": "Checkout Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(rate(response_time_ms_bucket[5m]))\r\n)",
     "legendFormat": "{{P99}}"
    }
   ]
  }
 ]
}